### ISSUE TITLE
software raids installed on boot,swap and root partitions with kickstart not working under el7

### ISSUE THREAD

**Issue by kwaegema** [quattor/aii#102]
raid .... --noformat seems not to assemble nor mount the used devices. This is only done when using  --useexisting

How I got it to work manually:
```
raid /boot --device=md1 --useexisting
raid swap --device=md3 --useexisting
raid / --device=md2 --fstype=ext4 --fsoptions='defaults' --useexisting
```
and in %pre section:
```
mdadm --stop /dev/md2
mdadm --stop /dev/md1
mdadm --stop /dev/md3
```

**Comment by jrha** [comment]
@stdweird has informed me that you have volunteered to fix this yourself :smile:

**Comment by jrha** [comment]
@kwaegema any update?

**Comment by jrha** [comment]
@kwaegema?

**Comment by jrha** [comment]
@kwaegema?

**Comment by kwaegema** [comment]
@jrha  I didn't test this yet with the new code, the fixes weren't specifically for this, so it is probable that it is not fixed completely, so I'll have to look/try again

**Comment by Pansanel** [comment]
I hit the same issue with CentOS7. I add this to the pre-section:
```
cat /proc/mdstat | grep md  | cut -d' ' -f1 | while read line; do
    mdadm --stop /dev/${line}
done
```
