### ISSUE TITLE
aii-opennebula: Update OpenNebula templates from configure hook

### ISSUE THREAD

**Issue by alvarosimon** [quattor/aii#107]
Right now ONE templates are generated from aii install hook. This is ok if we want to install and configure a new VM but if we want to update the templates or just generate templates without VM instantiation we should move these functions to be executed by configure hook instead install.

**Comment by jrha** [comment]
Fixed by #112.

**Comment by jrha** [comment]
@alvarosimon can you try to remember to include "fixes #nnn" (as documented [here](https://help.github.com/articles/closing-issues-via-commit-messages/)) in your PRs so the issues get closed automatically and I don't have to chase them down manually.
