### ISSUE TITLE
Bug in $logactions in %pre script

### ISSUE THREAD

**Issue by jnovy** [quattor/aii#110]
Hello,

there seem to be a bug in aii-ks code related to $logaction evaluation:
(and maybe a comment bug - see the first line with unfinished comment)

---
    # Takes care of the pre-install script, in which the
    sub pre_install_script
    {
    my ($self, $config) = @_;

    my $logfile = '/tmp/pre-log.log';
    my $logaction = log_action($config, $logfile);
    
    print <<EOF; 
    %pre
    # Pre-installation script.
    #
    # Block devices are created here instead of using Anaconda's
    # directives to allow better control. Anaconda doesn't guarantee that
    # the devices it creates will have the exact name it is told to. For
    # instance, if you define 4 primary partitions, it will create 3
    # primary, one extended and your /dev/foo4 will be silently renamed to
    # /dev/foo5.
    $logaction
    echo 'Begin of pre section'
    set -x
    EOF
---

what after aii-shellfe distills to:
---
    %pre

    # Pre-installation script.
    #
    # Block devices are created here instead of using Anaconda's
    # directives to allow better control. Anaconda doesn't guarantee that
    # the devices it creates will have the exact name it is told to. For
    # instance, if you define 4 primary partitions, it will create 3
    # primary, one extended and your /dev/foo4 will be silently renamed to
    # /dev/foo5.

    $logaction
    echo 'Begin of pre section'
    set –x
---

Note that $logaction is not evaluated. It is supposed to be:

---
    # Make sure messages show up on the serial console
    exec >/tmp/pre-log.log 2>&1
    tail -f /tmp/pre-log.log > /dev/console &
---

This causes we don't see the %pre script output on serial console... I will prepare a PR to fix this.

Thanks,
Jindrich

**Comment by stdweird** [comment]
@jnovy what OS/perl version is this? default for heredoc is to evalutae, maybe try with
```perl
print <<"EOF"; 
```
(don't know if it forces evaluation, but `'EOF'` certainly disables it).

**Comment by jnovy** [comment]
print <<"EOF";

won't even compile. I fixed it by creating separate print <<'EOF'; block and putting $logaction out from it. Sorry about old crappy perl version but we need to support it.

**Comment by jnovy** [comment]
(the perl version is 5.8.4)

**Comment by jouvin** [comment]
Which is coming from which OS version? I'd say that EL5 is probably a minimum to run AII and if I'm right it was already 5.8.10...

**Comment by stdweird** [comment]
@jnovy well, good luck with that then, because there' a lot of interpolated heredocs in AII ks.

**Comment by stdweird** [comment]
@jnovy can you also try with `${logaction}` (without quotes around the `EOF`)? this might also force interpolation

**Comment by jnovy** [comment]
Whoops - sorry the perl version is actually v5.10.1 (aii-shellfe asks for 5.10 specifically)

**Comment by stdweird** [comment]
and `print <<"EOF";` fails?

this is on EL6
```
[root@node2202 ~]# perl -e '$a=5; print <<"EOF"
> $a
> EOF
> '
5
[root@node2202 ~]# perl -v

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

Copyright 1987-2009, Larry Wall


```

**Comment by jnovy** [comment]
Yep, with print <<"EOF"; I get:

[ERROR] Couldn't load ks for path /system/aii/osinstall: Global symbol "$PATH" requires explicit package name at <path>/ks.pm line 705.

${logaction} won't help...

**Comment by jrha** [comment]
But but but...

```
# perl -e '$a=5; print <<"EOF"
> $a
> EOF
> '
5
# perl -v

This is perl, v5.8.0 built for i386-linux-thread-multi
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2002, Larry Wall
```

**Comment by jnovy** [comment]
Ok, that $PATH bits are downstream hack of my predecessor. It's not present in your code.

Sorry for the noise guys. I need to fix it in my downstream code.

The problem is that perl tries to evaluate $PATH as perl variable not the bash one...

**Comment by jrha** [comment]
Closed?
