### ISSUE TITLE
Idea: securing profiles and kickstart directories

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/aii#111]
Hi,
The 'profiles' and 'kickstart' directories are currently accessible through HTTP by at least every machine managed by AII. One problem I see is that a machine accessible by regular users could read all configuration information (including passwords, e.g. mysql) of all other machines.

I came up with a simple solution to isolate these files using an automatically-generated .htaccess file. Although not completely secure (regular users are still able to download the particular machine's configuration they are on), at least the information they have access to is much more limited.

Here's a sample secure.sh script I'm testing. I had a talk with @jouvin about it, who suggested me to submit my idea here to get feedback.

```
#!/bin/bash
# Directory containing the profile files
profilesDir='/var/www/html/profiles/'
# File type we're sure to meet in the directory
fileType='json'
for f in `ls $profilesDir/*.$fileType | xargs -n1 basename`; do
    host="${f%.$fileType}"
    h=`host $host | cut -d' ' -f4`
    echo -e "<FilesMatch $host.*>\n\tOrder deny,allow\n\tDeny from all\n\tAllow from $h\n</FilesMatch>"
done
```

I'm calling it this way:

```
secure.sh > /.../profies/.htaccess &
secure.sh > /.../kickstart/.htaccess &
```

There would be some changes to make in order to integrate it with AII, such as updating the .htaccess upon calling "configure" instead of regenerating everything (resolving hostnames could take a lot of time without a local DNS server).

Do you think it would be interesting to implement such idea into AII?

**Comment by StephaneGerardVUB** [comment]
Hi,
To prevent regular users from being able to access profiles and kickstart files, there is a solution based on freeipa that we use in belgian grid, but this solution is rather heavy and complicated. You will find a short description of what we did here : http://mon.iihe.ac.be/trac/t2b/wiki/QuattorFreeIPA. It is not high quality and up-to-date documentation, but at least, it gives you a sketch of the way to go, if you really want to go this way.
Cheers,
Stéphane

**Comment by stdweird** [comment]
@JulienNauroy to achieve this we use httpd rewrite rules and certificates (from sindes for now, looking into freeipa to replace sindes), and the the requests are mapped to the hostname in the certificate).

so the writeup from @StephaneGerardVUB is more or less what we are using now and what we will be using later (we might look into using krb5 credentials only, but that's a minor difference; and i'm not sure we can make it work :smile: )


for kickstart files, you can't use https, but you can map/rewrite the request IP to the hostname. but you should not consider kickstart files as secure (even with this trick). e.g. we use a AII kickstart root password hash and once quattor passes by it sets a different root password. same should occur for any other sensitive data (e.g. the grub password).

**Comment by jrha** [comment]
We did something similar that used a redirect rule to redirect any request (for any URL) to `/profiles/$HOSTNAME`.json where `$HOSTNAME` is the result of a reverse lookup of the request IP, the advantage here is that it can be configured statically.

I'll see if I can find it.

**Comment by jrha** [comment]
Can't find it, but it was something like:
RewriteRule ^(.*)$ https://%{HTTP_HOST}/profiles/%{REMOTE_HOST}.json
which also forces use of HTTPS.

**Comment by jrha** [comment]
Also, you don't need to configure CCM on clients properly anymore, just point them at `https://quattorserver.example.org/myprofile`, oh it's nasty sure, but so very lazy.

**Comment by piojo** [comment]
[Pan template](https://github.com/stdweird/quattor-SCDB-ugent/blob/master/cfg/non-grid/hpc/common/quattor-server/profiles.pan) with the UGent's configuration.

The `ACLmap` file allows certain hosts to look at all profiles. This is useful for the AII server, unless it runs in the same host that serves the profiles, in which case using `file://` URLs is faster.

**Comment by jrha** [comment]
Nice, I like the way it handles the extension correctly :+1:

**Comment by JulienNauroy** [comment]
Thanks for all your comments.
Will we see any of these solutions implemented in a next release (e.g. solutions proposed by @StephaneGerardVUB and @stdweird)? Or maybe added to the tuturial as a good practice, such as @jrha's solution (which is way better than mine, I'll use it!)

**Comment by jrha** [comment]
It could certainly go into the tutorial and/or examples.

I think this is the best bits of mine and the UGent rules (but haven't tested it) I think it should handle everyone's use cases though.

```apacheconf
# The following ACL map can be used to specify hosts which can access all profiles
RewriteMap ACLmap txt /var/www/acl/ACLmap.txt
RewriteCond ${ACLmap:%{REMOTE_HOST}|NO} NO

RewriteRule  ^/profiles/.*\.(xml|json)(\.gz)?$ https://%{HTTP_HOST}/profiles/%{REMOTE_HOST}.$1$2' [L]
```

**Comment by JulienNauroy** [comment]
I think your example generates an infinite loop because of the HTTP 302 redirection.
I'd try something like:
``` apacheconf
RewriteEngine On
# The following ACL map can be used to specify hosts which can access all profiles
RewriteMap ACLmap txt:/var/www/acl/ACLmap.txt

# Redirect every profile request to HTTPS
RewriteCond %{HTTPS} !=on
RewriteRule  ^/profiles/(.*)$ https://%{HTTP_HOST}/profiles/$1 [L]

# Serve only the profile corresponding to the remote host if the host is not part of the ACLmap
RewriteCond ${ACLmap:%{REMOTE_HOST}|NO} NO
RewriteRule  ^/profiles/.*\.(xml|json)(\.gz)?$ /profiles/%{REMOTE_HOST}.$1$2 [L]

# Serve only the kickstart corresponding to the remote host if the host is not part of the ACLmap
RewriteCond ${ACLmap:%{REMOTE_HOST}|NO} NO
RewriteRule  ^/kickstart/.*\.ks$ /kickstart/%{REMOTE_HOST}.$1.ks [L]
```

Not tested yet, I didn't order the SSL certificate for my machine yet. I'll test it and improve it if need be so that it can be added to the tutorial.

**Comment by JulienNauroy** [comment]
I've just tested it, seems to work well.
