### ISSUE TITLE
questions around wipe_metadata

### ISSUE THREAD

**Issue by kwaegema** [quattor/aii#115]
There are some things in the generated kickstart files that needs some cleanup:
- `wipe_metadata` only has 1 parameter, the device. But it is further called with an additional value , eg:
 `wipe_metadata /dev/sda1 1`
- the `if [ primary != "extended" ]` wrapped around `wipe_metadata` : Should `primary` be a string or a variable? don't know where this should come from.

**Comment by stdweird** [comment]
to answer the questions: 
a. the second parameter is the `clear_mb`, the minimum amount of data to write (affected by offset and/or alignment)
b. fixed that bug

**Comment by stdweird** [comment]
@kwaegema need anything else?

**Comment by kwaegema** [comment]
Nope, that clears it up, thanks!
