### ISSUE TITLE
aii-ks 15.4: missing CR in messages displayed at the console 

### ISSUE THREAD

**Issue by jouvin** [quattor/aii#120]
I don't know if this is specific to our HW but with `aii-ks` 15.4 (may be also the case with previous version...) when installing EL7, with graphic mode disabled (the default), all the messages printed during KS pre/post scripts are missing a CR (only the LF is taken into account). The result is hardly readable. Something like:

```
message text first line
                       message text second line
                                                yet another line
```

Is it a know problem? Are we the only one with it?

**Comment by stdweird** [comment]
messages printed where? in our case, both local logfiles and the remote logger output looks ok.

also, is this 7.0 anaconda or 7.1? and do you have any localisations enabled?
is there anything funny with the kickstart file itself? (maybe something slipped in there, some non-US locale setting transferred via ssh environment; and picked up by aii-shellfe?; ssh from iOS is known to cause problems with locale settings in editors)

**Comment by jouvin** [comment]
Sorry, I forgot to mention that the problem is on the console. I can imagine that this is perfectly correct in files (as LF is the Unix end-of-line mark). I have not seen this problem before (in SL6): for example the pre script commands and command output were printed fine on the console. I don't think it has to do with localisation as we are using US locale:

```
lang en_US
keyboard --xlayouts=us
```

**Comment by stdweird** [comment]
@jouvin with console you mean serial console or an actual terminal? i found a screen resolution mismatch issue https://bugs.centos.org/view.php?id=7313, maybe worth a try?

**Comment by jouvin** [comment]
Yes serial console...I had a quick look to the url you mention but I am not sure this is the same problem...

**Comment by jrha** [comment]
We have seen this too.

**Comment by jnovy** [comment]
The printing issue on the serial console without CR seems to be related to anaconda pane setup. Asked Red Hat about it. I will let you know.

**Comment by jnovy** [comment]
Red Hat suggested e.g. this structure to process CR properly:

%pre 
(
echo 'Pre Script'
echo  'Foo...'
echo -en 'Bar..\nTesting\n'
echo -en '1 '
echo -e '2...'
) 2>&1 | tee /tmp/pre.log | tee /dev/pts/0
%end

I tested it and it works.

**Comment by jouvin** [comment]
Would be good to implement it! This is making debugging much harder...

**Comment by jouvin** [comment]
Fixed in recent Quattor versions.

**Comment by stdweird** [comment]
@jouvin what PR/commit?

**Comment by jouvin** [comment]
My mistake, I was sure it was working properly but in fact installing an EL7 machine today, I saw that this was not the case. Is there any possible fix other than defining an `echo` function that will had the missing CR ?
