### ISSUE TITLE
Add a reinstall option

### ISSUE THREAD

**Issue by samary** [quattor/aii#126]
Hi,

On our site, when we want to reinstall a node, we run successively 3 commands : 
- `aii-shellfe --remove $node` to clean things up.
- `aii-shellfe --configure $node` to create all needed files, entries, ...
- `aii-shellfe --install $node` to set the node to install at next boot.

Therefore, I think it could be useful if we have a one-liner `aii-shellfe --reinstall $node` option to do the same.

Inspired by #124

**Comment by jrha** [comment]
We use the `rci` alias from UGent for this.
