### ISSUE TITLE
Missing freeipa.pm in AII RPM

### ISSUE THREAD

**Issue by samary** [quattor/aii#134]
Hi,

I was wondering why the `aii-freeipa/src/main/perl/freeipa.pm` is not included in the latest RPM release (15.4.0) ?
Is it a mistake or this should come via another RPM (like aii-freeipa) not available yet ?

Cheers

**Comment by stdweird** [comment]
the `freeipa` rpm is not part of the release, mainly because the build step currently produces unusable rpm for EL7 based systems.

**Comment by samary** [comment]
Thanks for the answer.
How can I build this RPM on my laptop to test things ?

**Comment by stdweird** [comment]
regular `mvn package`, use the instructions in the README if you are not using python 2.6

**Comment by samary** [comment]
Nice :D 
Should I close this or keep it open for tracking ?

**Comment by stdweird** [comment]
leave it open, i'll try to look at this for 15.10

**Comment by samary** [comment]
Up ?

**Comment by stdweird** [comment]
@samary the freeipa AII module is now part of the freeipa component. this is not needed anymore afaik

**Comment by samary** [comment]
@stdweird : Ok, we will try it.
