### ISSUE TITLE
AII not using excludedPackages?

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/aii#151]
Hi,

Following this thread: https://github.com/quattor/ncm-ncd/issues/52
It looks like AII understands specifying exact versions of packages through `pkg_replace` but does not take `excludepkgs` directives from repository declarations into consideration.

One consequence is AII not able to run ccm-fetch when some repository overrides perl-common-sense and puts files in another place.

Since I'm able to reproduce this error on my side, I can run tests and give more information upon request.

Cheers,
Julien

**Comment by stdweird** [comment]
Feel free to try the patch in #152 and report back if it works or not.
