### ISSUE TITLE
aii-ks: aii repository creation during install does not escape variables

### ISSUE THREAD

**Issue by wdpypere** [quattor/aii#153]
In the kickstart scripts, at a certain point we do:
```
mkdir -p /tmp/aii/yum/repos
cat <<end_of_yum_conf > /tmp/aii/yum/yum.conf
[main]
cachedir=/var/cache/yum/$basearch/$releasever
```
which results in:
```
cachedir=/var/cache/yum//
```

Not game breaking but it is not correct and leaves stuff on the system which should not be there. Escaping these should work.

**Comment by stdweird** [comment]
@wdpypere can you apply the patch by hand and verify?

**Comment by wdpypere** [comment]
@stdweird will do

**Comment by wdpypere** [comment]
@stdweird tested and it works as expected.
