### ISSUE TITLE
Usage of aii-core dhcp and aii-dhcp

### ISSUE THREAD

**Issue by kwaegema** [quattor/aii#166]
Hi,
when trying to solve #150 , I stumbled over something looking strange: I found the logic to configure dhcp in two different places:
https://github.com/quattor/aii/blob/master/aii-dhcp/src/main/perl/dhcp.pm
https://github.com/quattor/aii/blob/master/aii-core/src/main/perl/aii-dhcp

At first sight, they seem to have the same functionality, functions and identical implementations. Only the way of calling these differs: aii-dhcp in aii-core is to be called as command line script, where the aii-dhcp module has the known Configure/Unconfigure subs. 

I see in aii-shellfe the aii-dhcp of aii-core is used by calling the program with CAF. I don't find the other aii-dhcp module used somewhere.

My questions:
- Is there a reason we have two implementations for this ? 
- Why don't we use the aii-dhcp module Configure/unconfigure methods in aii-shellfe ? Then we would also see the output of aii-dhcp when running aii-shellfe. (Right now, the output of aii-dhcp is captured by aii-shellfe and logged on debuglevel 4, so warnings of aii-dhcp are only shown in debuglevel 4)

**Comment by gombasg** [comment]
I think we have integrated the DHCP bits into AII and pushed that upstream, but the old stand-alone script was left in place to help the transition. That was a long time ago, and I don't know if others switched to the AII module or not.

**Comment by kwaegema** [comment]
@gombasg I digged a bit into it, and in the aii-shellfe script I see it is possible to use the AII module as pluging when /system/aii/discovery/.. is used (https://github.com/quattor/aii/blob/0a44ed80a89f04e98f67a2a32855a4449fa9df7d/aii-core/src/main/perl/aii-shellfe#L772). 
This is also mentioned in the oldest issue #1 . (Don't know if this is still valid, but it seems so)
So we should move in that direction imho..
Now I looked through the quattor repos to find the schema that declares the /system/aii/discovery path, but I don't seem to find it.. Can you point me to where to find this?
If I understand correctly, you are succesfully using the module plugin? 
In that case I suggest we deprecate /system/aii/dhcp in favor of /system/aii/discovery/dhcp ?

**Comment by stdweird** [comment]
afaik, this is the situation:
* there's a script `aii-dhcp` uses DHCP from aii-core
* aii-shellfe uses DHCP.pm directly (not via the script)
* aii-dhcp is a plugin/hook that is not used by default in AII (and unmaintained?)

proposal: get rid of unused plugin/hook under aii-dhcp

**Comment by jrha** [comment]
Discussed at March 2017 workshop, agreed to remove the script and review the differences between the module and plugin.

**Comment by jrha** [comment]
We appear to be using the plugin at RAL and MS definitely are (they contributed it).
