### ISSUE TITLE
Support kerberised ccm 

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#168]
* generate the principal / keytab entry in ccm.conf https://github.com/quattor/CCM/pull/93
* rework/update the aii-freeipa hooks

**Comment by stdweird** [comment]
in particular aii-freeipa is not ready at this moment

**Comment by jrha** [comment]
In terms of "not ready", do we have a list of what is missing?

**Comment by stdweird** [comment]
@jrha if https://github.com/quattor/aii/pull/161 gets merge, it should support the required params for ccm.conf in aii.

it is also possible that the old aii-freeipa still works, but the new one is not ready yet.

so your mileage may vary; in particular i have not tested anything with AII yet

**Comment by jrha** [comment]
Not "supported" until aii hooks are reworked, bumping.

**Comment by stdweird** [comment]
@jrha i just managed to deploy el6 and el7 node using AII and ccm with kerberos auth (based on ipa).  there is nothing missing anymore in AII, CCM or CAF. for ipa suport itself, there's https://github.com/quattor/aii/pull/203 and the IPA PR itself https://github.com/quattor/configuration-modules-core/pull/750; but that's probably outside the scope of this issue.

**Comment by jrha** [comment]
Ok, then this is done!
