### ISSUE TITLE
aii forces CDB_File

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#175]
AII has a requirement on CDB_File, as it passed as an option to CCM, but not used in aii itself.
my question: should aii really use something else than the local CCM? (and if CDB_File really is faster/better/..., why is it not the default in CCM, or a requirement/dependency of CCM)

**Comment by jrha** [comment]
I think I remember @njwilliams and/or @gombasg having opinions on CDB_File.

**Comment by njwilliams** [comment]
When used as a server_module, AII runs against a large number of cached profiles. No matter what the general use-case of CCM (e.g. on a specific host, it might have GDBM or something), when in the use-case of processing many profiles then CDB was an order of magnitude faster. This was a write-up in one of the QWG meetups - see the 'Bootserver' section at https://trac.lal.in2p3.fr/Quattor/wiki/Meetings/Workshops/20081027#MorganStanley-N.Williams. Therefore we forced AII to use CDB.

At the time, we did not want to force all CCM use-cases to switch format. No good reason why not other than FUD.

**Comment by stdweird** [comment]
@njwilliams thanks for the clarification
http://www.perlmonks.org/bare/?node_id=1023711, showing that CDB is really a lot faster. since we use the DB as WORM, CDB seems like the best fit.
i opened https://github.com/quattor/CCM/issues/100 to track this

**Comment by gombasg** [comment]
Actually, we're considering switching to CDB for CCM too, because we ran into issues with the BDB backend when the disk fills up. I don't remember the details right now, but I _think_ the issue was that BDB simply did not notice when the disk got full, and we ended up with corrupt state without any indication of an error.

**Comment by stdweird** [comment]
Default has been changed in CCM
