### ISSUE TITLE
Missing dependency requirement perl-XML-Simple

### ISSUE THREAD

**Issue by jouvin** [quattor/aii#188]
`aii-shellfe` in 16.6.0 requires `perl-XML-Simple`. This needs to be added to the `pom` file.

This is a showstopper for [16.6.0](https://github.com/quattor/release/issues/253).

**Comment by stdweird** [comment]
@jouvin this is odd. i get the following with an rpm that was build before 
```
 rpm -q --requires aii-server | grep -i Simple
perl(XML::Simple)  
```
can you check if this requirement was not set in the old rpm?
