### ISSUE TITLE
slow aii-shellfe

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#193]
* with tabcompletion enabled by default in ccm, extra unnecessary work is done (30-40% of single node work)

**Comment by jrha** [comment]
I'm not sure what this means, but it doesn't sound good.

**Comment by stdweird** [comment]
fix for current release: https://github.com/quattor/aii/blob/master/aii-core/src/main/perl/aii-shellfe#L931 insert 
```perl
 print $cfg_fh "tabcompletion 0\n";
```

due to #190, i'm not going to make PR for this; but will fix it in that PR.

**Comment by stdweird** [comment]
Fixed in https://github.com/quattor/aii/pull/190/commits/d65d63ba3471729d12f45820f621ab57fff03b30 which is part of #190
