### ISSUE TITLE
aii-core: issue when the main tree has more than one entry in "/system/aii/nbp"

### ISSUE THREAD

**Issue by Pansanel** [quattor/aii#200]
Hi,

We need to set for disabling bonding during boot time:

```
"/system/aii/nbp/ks/info/bonding" = false;
```

After compilation, the configuration tree contains a supplementary element `ks`:

```
     "nbp": {
        "ks": {
          "info": {
            "bonding": false
          }
        },
        "pxelinux": {
          "initrd": "sl680_x86_64/initrd.img",
          "kernel": "sl680_x86_64/vmlinuz",
          "ksdevice": "12:34:56:65:43:21",
          "kslocation": "http://quattor.example.org/ks/wn1.example.org.ks",
          "label": "Scientific Linux 680 (x86_64)"
        }
      },
```

In this case, the `aii-shellfe` fails with the following error:

```
[DEBUG] Instantiating ks
[DEBUG] no method Install available for plugin ks
```

This is caused by the line https://github.com/quattor/aii/blob/master/aii-core/src/main/perl/Shellfe.pm#L363 where the perl script is running the ks plugin instead of pxelinux plugin!
Setting the plugin name from a position in a key list is not safe. Is there a case where the name of the plugin is not **pxelinux**?

**Comment by jrha** [comment]
This is what I would expect! Setting
```pan
"/system/aii/nbp/ks/info/bonding" = false;
```
to me, disables bonding during kickstart, not boot.

What behaviour are you actually trying to achieve?

**Comment by jouvin** [comment]
@Pansanel I am not sure what you want to do but is not it `/system/aii/osinstall/ks` that you would like to set. I have the feeling that `/system/aii/nbp` can accept any key and that just `nbp` has a schema, thus the reason it compiled.

**Comment by jouvin** [comment]
I just checked, `/system/aii` is basically defined as `extensible` in `quattor/types/aii.pan`. And then the parts really used are assigned a schema that restricts what is possible. The end result is that you cannot catch misdefined paths... Personally I never liked this and this is probably something that should be revised at some point... At least to restrict what is extensible.

**Comment by Pansanel** [comment]
Using ```"/system/aii/nbp/ks/info/bonding" = false;``` makes ```aii-shellfe --install``` failing silently (you only see "no method Install available for plugin ks" with debug enabled.
If nbp can accept any key, we should modify:
```
my $modulename = (keys (%rm))[0];
```
with
```
my $modulename = 'pxelinux';
```
(or better, passing the name of the module to the function **run_plugin**).

**Comment by stdweird** [comment]
@jouvin :+1: on not liking any extensible type
@Pansanel as @jouvin said, disabling bonding in ks should be done with `'/system/aii/osinstall/ks/bonding' = false;` (see unittest https://github.com/quattor/aii/blob/master/aii-ks/src/test/resources/kickstart_bonding.pan)

out of interest, may i ask why you are disabling bonding? what is not working when it's enabled?

**Comment by Pansanel** [comment]
When it is enabled, I can not you mac address at ksdevice.

**Comment by stdweird** [comment]
@Pansanel please elaborate :smile: so it generates pxe boot args that do not work? (can you paste them here?)

**Comment by Pansanel** [comment]
When I use the following code:
```
"/system/aii/nbp/pxelinux/ksdevice" = value ("/hardware/cards/nic/" + boot_nic() + "/hwaddr");
```

```aii-shellfe --configure``` fails with the following error:
```
...
[ERROR] Invalid ksdevice 12:34:56:65:43:21 for bonding network configuration. 
...
```

**Comment by stdweird** [comment]
@Pansanel 
* do you actually have bonding configured on that host? if not, this is a bug in the pxelinux code that you cannot pass a macaddress as ksdevice (it's definitely a bug i think), as that should (still?) work. (i've never configured `ksdevice=<macaddress>` myself; but i assume it used to work since you are using it)
* if you do have bonding and want it configured during anaconda (that's what the bondig=true is all about), i'm not sure how we can handle passing a macaddress as ksdevice.

* out of interest, why don't you use `"/system/aii/nbp/pxelinux/ksdevice" = boot_nic();` instead of the macaddress? it's possible that anaconda messes up the device naming, but i haven't seen this in a long time myself

**Comment by stdweird** [comment]
@Pansanel how did the `aii-shellfe` "fail"? did it only report the error? (code looks like it should have generated the correct pxe cfg file). (anyway, i'll fix this)

**Comment by jrha** [comment]
@Pansanel @stdweird did you get any further with this?

We've spawned a few issues during the investigation, will fixing them address the root problem or do we still need this as a top level issue?

**Comment by jouvin** [comment]
The main issue remaining is tracked in https://github.com/quattor/aii/issues/201. I'd suggest to close this one that has too many things in it.

**Comment by jrha** [comment]
Replaced by #201.
