### ISSUE TITLE
aii-opennebula: missing dependency

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/aii#214]
Release 16.8.0 of aii-opennebula RPM requires perl-Net-OpenNebula >= 0.307.0 which is not available in the quattor repositories.

**Comment by alvarosimon** [comment]
Ah yes, it's available from CPAN but not from quattor repos, @stdweird it would be possible to include the new `perl-Net-OpenNebula` version in quattor repositories?

**Comment by stdweird** [comment]
@StephaneGerardVUB http://users.ugent.be/~stdweird/quattor_externals/noarch/perl-Net-OpenNebula-0.308.0-1.noarch.rpm
@jrha @jouvin who controls the quattor externals repo again?

**Comment by jrha** [comment]
Controls... :laughing:... I can put it there.

**Comment by jrha** [comment]
Done.

I've also added panc 10.3 to all the externals repos.

**Comment by stdweird** [comment]
It's in the http://yum.quattor.org/externals/noarch/el7/ and el6 repo.
@jrha thanks
