### ISSUE TITLE
16.10 snapshot: aii-ks unit tests failing on a SL6 machine

### ISSUE THREAD

**Issue by jouvin** [quattor/aii#219]
I don't manage to get the aii-ks unit tests passing on my SL6 development machine (16 tests are failing), despite they work properly on Jenkins. Log is attached
[log.gz](https://github.com/quattor/aii/files/566621/log.gz)

**Comment by stdweird** [comment]
Quick scan shows you need more up-to-date ncm-lib-blockdevices. latest master https://jenkins1.ugent.be/view/Quattor/job/ncm-lib-blockdevices/lastSuccessfulBuild/org.quattor.maven$blockdevices/artifact/org.quattor.maven/blockdevices/16.8.1-SNAPSHOT/blockdevices-16.8.1-SNAPSHOT.rpm
Jenkins uses master of everything to test

**Comment by jouvin** [comment]
I checked but this is what I was using (if I have not done any mistake!). Don't worry too much for this, I can wait for the RC to check that everything works as expected when everything is at the same version.

**Comment by stdweird** [comment]
hmm, it is strange. all failures are related to `extended_no_msdos_label` which was introduced in  https://github.com/quattor/ncm-lib-blockdevices/pull/51

i just ran all tests on el5/6/7, they all passed (see https://github.com/quattor/release/pull/265)

**Comment by jouvin** [comment]
Another mistake of mine!!! Sorry for the noise...
