### ISSUE TITLE
shellfe-dhcp.t attemps to open an unexisting config file

### ISSUE THREAD

**Issue by jouvin** [quattor/aii#250]
Looking at aii-core tests, I found that `shellfe-dhcp.t` attempts to open an unexisting AII config file (`shellfe.cfg`). This doesn't cause the test to fail but I have the feeling this is unexpected and probably the result of a renamed `.cfg` file... If this is done on purpose feel free to close this issue after adding a comment in the test...

**Comment by stdweird** [comment]
@kwaegema did you forget to commit this file?
