### ISSUE TITLE
remove aii-opennebula and move all issues to the component

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#252]
both aii-opennebula and ncm-opennebula now generate the `quattor/aii/opennebula` templates, and only the component is supported.

the subdir can be deleted, and the `aii-opennebula` entry must be removed form the main project pom.xml.

also any leftover issues have to be closed or transferred to the component repo

**Comment by alvarosimon** [comment]
Old  opennebula aii issues are now closed or reassigned to the component, I will open a new PR to remove opennebula aii..
