### ISSUE TITLE
number prefix in message for no apparent reason

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#257]
probably the parallel forkmanager adds these, but this is on a config where no parallel was defined in the config

eg the `1` befroe the `AII::DHCP`
```
[INFO] 1AII::DHCP: config /etc/dhcp/dhcpd.conf changed, ....
```

**Comment by stdweird** [comment]
Not sure if this is a blocker for https://github.com/quattor/release/issues/285
@jrha i'll let you decide
@kwaegema can this fixed quickly?

**Comment by jouvin** [comment]
This is probably a typo with a debug() changed to info() keeping the debug level. Should be trivial to fix.

**Comment by jrha** [comment]
Good catch!
Definitely not a blocker, but should be fixed because it should be simple to do so.

**Comment by jouvin** [comment]
A mistake that I did more than once!
