### ISSUE TITLE
aii pxelinux write failure

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#258]
related to #225

ugly failure due to missing function/method?
```
[ERROR] Failed to execute plugin module's pxelinux Configure method
[ERROR] Errors running plugin module pxelinux Configure method: Undefined subroutine &NCM::Component::pxelinux::write_pxelinux_config called at /usr/lib/perl/NCM/Component/pxelinux.pm line 720.

[INFO] ran configure on 1 nodes
[INFO] install step for reinstall option.
[INFO] Detected domainname within configfile RPC section: [banette.os]
[INFO] Detected OpenNebula version: 5.2.1
[ERROR] VM template is not available to instantiate VM: test2801.banette.os
[INFO] ran install on 1 nodes
Uncaught exception!!! Calling stack is:
  LC::Fatal::symlink called at /usr/lib/perl/NCM/Component/pxelinux.pm line 578
  NCM::Component::pxelinux::__ANON__ called at /usr/lib/perl/AII/Shellfe.pm line 494
  AII::Shellfe::__ANON__ called at /usr/lib/perl/AII/Shellfe.pm line 1087
  AII::Shellfe::cmds called at /usr/sbin/aii-shellfe line 352
*** symlink(test2801.banette.os.cfg, /osinstall/nbp/grub-efi/grub.cfg-0A8D15C9): No such file or directory
```

**Comment by stdweird** [comment]
@jouvin

**Comment by stdweird** [comment]
@jouvin this is during a reinstall, no uefi settings applied yet

**Comment by stdweird** [comment]
fixed with comments in PR https://github.com/quattor/aii/pull/225/files#r103927865 and https://github.com/quattor/aii/pull/225/files#r103927717

**Comment by jouvin** [comment]
I apologize about this. I did this yesterday evening and I was sure that I installed the new version since then... Clearly not. And I was sure that a typo would be catched by unit tests when these methods are not. PR #255 fixed now. Unit test still to be added: I keep this issue open until it is done.

**Comment by jrha** [comment]
@stdweird was this in master or were you testing #225?

**Comment by stdweird** [comment]
testing #225, and is already fixed there. @jouvin wanted to keep this open, but it can already be closed afaik

**Comment by jouvin** [comment]
#225 is supposed to close this issue... but I have no problem if you close it before...
