### ISSUE TITLE
aii-ks: xwindows default configuration for SL7 is wrong

### ISSUE THREAD

**Issue by nowack73** [quattor/aii#262]
In quattor/aii/ks/schema.pan,  '/system/aii/osinstall/ks/xwindows/depth' is set to 24 by default. This produces in the kickstart file a line with "xconfig .... --depth=24". In SL7, anaconda complains about the unknown option "--depth" and quits the installation.

According to [RHEL5 kickstart options](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Installation_Guide/s1-kickstart2-options.html), [RHEL6 kickstart options](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s1-kickstart2-options.html), and [RHEL7 kickstart options](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/sect-kickstart-syntax.html), only RHEL5 supports the option '--depth' officially.

**Comment by nowack73** [comment]
Futthermore, the option "--resolution=" is not supported in RHEL6 and RHEL7 and therefore should not be mandatory.

**Comment by jrha** [comment]
Default should be removed from schema, only in el5 variant.

**Comment by stdweird** [comment]
@jrha @jouvin there is no el5 variant file atm. what should we call it: `sl5` or `el5`?

**Comment by jrha** [comment]
IMHO it should match the template library branch naming convention (i.e. sl5).
