### ISSUE TITLE
aii-ks: new ack list feature has wrong pan code

### ISSUE THREAD

**Issue by stdweird** [quattor/aii#317]
https://github.com/quattor/aii/pull/305/files#diff-8d164602489699c4ecacdfc3ba849cd4R393

the `value` call needs a default `undef` value, otherwise, value will trigger an error.
but there are some other things odd:
- why use value if the value is set the line above using a variable (should that have been a `?=` ?)
- the logic order of the blocks should be switched

**Comment by gombasg** [comment]
I've stared at the templates for a while, and then decided that deprecating ackurl would be the best way forward. I believe the PR I've opened should not cause any incompatibility, but that needs to be tested outside of our environment...
